Feature/example properties
UUDigitalHumanitieslab/gretel pull request #249
Opened 2022-02-01 10:08 UTC by oktaal

![Screenshot 2022-02-01 at 11 03 56](https://user-images.githubusercontent.com/24268578/151948910-36ddc9f0-08a9-423f-9f48-62148b382b44.png)

Uses [alpino-query](https://github.com/UUDigitalHumanitieslab/alpino-query) instead of the built-in generator.

2022-02-02 19:48 UTC, jgonggrijp commented
Sexy table.

2022-02-03 21:12 UTC, oktaal commented
Deployed on https://tst.gretel.hum.uu.nl

2022-02-14 17:13 UTC, JeltevanBoheemen requested changes
(alles getest op tst.gretel/hum/uu/nl)

Tooltips groeien uit hun ballonetjes:
![image](https://user-images.githubusercontent.com/4539142/153910513-3e01442c-0e87-4adf-a567-66ed88c1fde9.png)

Er is me niet meteen duidelijk wat de kleuren betekenen. Vooral geel (rood en groen zijn wat meer obvious). Misschien kleine legenda?

De iconen ontbreken bij mij, zitten wel in de DOM maar niet zichtbaar. Dat fixed mogelijk bovenstaand:
![image](https://user-images.githubusercontent.com/4539142/153911634-33892b53-a99e-4d69-a84f-7925fd265005.png)

Code is heel nice. Fijn dat Perl eruit is, goed werk met die alpinoquery!

2022-02-21 17:10 UTC, JeltevanBoheemen commented
Jep, stukken duidelijker. Nu worden de knoppen echter niet groen als ze op required staan.

2022-02-23 09:14 UTC, oktaal commented
Het 'probleem'/feature is dat ik bij de standaardwaarde van iedere eigenschap het grijs laat:

![image](https://user-images.githubusercontent.com/24268578/155288148-9987c235-ce6a-433e-b1a8-a5606a63d85e.png)

Ik kan ook altijd een kleurtje geven op basis van de waarde, maar dan wordt het een kermis:

![image](https://user-images.githubusercontent.com/24268578/155289534-fb4e7878-be1f-4775-a653-06316e06570a.png)

Misschien nog een beetje binnen de perken te houden door wat te tweaken:

`is-outlined`
![image](https://user-images.githubusercontent.com/24268578/155289694-c09c2771-3339-4b1b-bdce-61d34a0516c4.png)
`is-light`
![image](https://user-images.githubusercontent.com/24268578/155289957-6708d0c1-8c29-4d9b-afe9-2e70791d7703.png)

Of door bijvoorbeeld alleen een kleur te geven als de waarde ooit gewijzigd is (maar dan is het gedrag helemaal ondoorgrondelijk).

2022-02-24 17:58 UTC, JeltevanBoheemen commented
Eens over de kermis. `is-outlined` vind ik wel een goede optie.

2022-03-02 12:56 UTC, merged